language: node_js
node_js:
- "5.9.1"
sudo: false
services:
- docker
cache:
  directories:
  - node_modules
  - vendor/bundle
before_install:
- rvm install 2.2.2
- rvm use 2.2.2
- gem install bundler
- bundle install --path vendor/bundle
script:
- ./scripts/deploy-to-staging.sh
deploy:
  skip_cleanup: true
  provider: script
  script: rvm 2.2.2 do ./scripts/deploy.sh
  on:
    branch: source
