language: node_js
node_js:
- "5.9.1"
sudo: false
cache:
  directories:
  - node_modules
  - vendor/bundle
before_install:
- rvm install 2.2.2
- rvm use 2.2.2
- gem install bundler
- bundle install --path vendor/bundle
deploy:
  provider: script
  script: rvm 2.2.2 do ./scripts/deploy.sh
  on:
    branch: source
